title: "Foundations of Data Science"
description: CSC 10800 @ CCNY 
theme: just-the-docs
url: https://zmuhls.github.io/ccny-data-science
baseurl: "/CCNY-Data-Science"
repository: zmuhls/ccny-data-science

permalink: pretty

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

aux_links:
  "zmuhls/CCNY-Data-Science on GitHub":
    - "https://github.com/zmuhls/ccny-data-science"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

heading_anchors: true

#Back to the top link
back_to_top: true
back_to_top_text: "Back to top"
